{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "87fc6e0a-0b59-4dd3-9239-e36d71bce3fd",
   "metadata": {},
   "outputs": [],
   "source": [
    "from basepokemon import BasePokemon, BaseMove, Type\n",
    "\n",
    "class Pokemon(BasePokemon):\n",
    "    def __init__(self):\n",
    "        BasePokemon.__init__(self)\n",
    "        # Has to sum to 100\n",
    "        self.spend_hp(30)\n",
    "        self.spend_attack(30)\n",
    "        self.spend_defence(40)\n",
    "        self.add_move(Aumento_de_sueldo())\n",
    "        self.add_move(Cubiculo_gris())\n",
    "        self.add_move(Reunion_aburrida())\n",
    "        self.add_move(Indigestion_en_la_oficina())\n",
    "        self.set_type(Type.NORMAL)\n",
    "        self.move = 0\n",
    "        self.moves = ['Aumento_de_sueldo', \"Cubiculo_gris\", \"Reunion_aburrida\", \"Indigestion_en_la_oficina\"]\n",
    "\n",
    "\n",
    "    def get_name(self):\n",
    "        return \"Oficinista_frustrado\"\n",
    "\n",
    "    def choose_move(self, enemy):\n",
    "        mov = self.moves[self.move]\n",
    "        self.move = self.move + 1 if self.move < len(self.moves) - 1 else 0\n",
    "        return self.get_move_by_name(mov)\n",
    "\n",
    "class Aumento_de_sueldo(BaseMove):\n",
    "    def __init__(self):\n",
    "        BaseMove.__init__(self)\n",
    "        self.choose_uses(1)\n",
    "        self.set_type(Type.NORMAL)\n",
    "\n",
    "    def get_name(self):\n",
    "        return \"Aumento_de_sueldo\"\n",
    "\n",
    "class Cubiculo_gris(BaseMove):\n",
    "    def __init__(self):\n",
    "        BaseMove.__init__(self)\n",
    "        self.choose_uses(1)\n",
    "        self.set_type(Type.NORMAL)\n",
    "\n",
    "    def get_name(self):\n",
    "        return \"Cubiculo_gris\"\n",
    "\n",
    "\n",
    "class Reunion_aburrida(BaseMove):\n",
    "    def __init__(self):\n",
    "        BaseMove.__init__(self)\n",
    "        self.choose_uses(1)\n",
    "        self.set_type(Type.NORMAL)\n",
    "\n",
    "    def get_name(self):\n",
    "        return \"Reunion_aburrida\"\n",
    "\n",
    "\n",
    "class Indigestion_en_la_oficina(BaseMove):\n",
    "    def __init__(self):\n",
    "        BaseMove.__init__(self)\n",
    "        self.choose_uses(1)\n",
    "        self.set_type(Type.FIRE)\n",
    "\n",
    "    def get_name(self):\n",
    "        return \"Indigestion_en_la_oficina\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4d909b24-a308-40b9-87d3-b7291880a1dc",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
